export const featureConfig = {
  'employees': {
    title: 'Employees',
    singular: 'Employee',
    apiKey: 'employeesAPI',
    hasAI: false,
    getItemTitle: (item) => item.name,
    columns: [
      { key: 'employeeId', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'department', label: 'Department' },
      { key: 'position', label: 'Position' },
      { key: 'shift', label: 'Shift', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'employeeId', label: 'Employee ID', type: 'text', required: true },
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'text', required: true },
      { key: 'position', label: 'Position', type: 'text', required: true },
      { key: 'shift', label: 'Shift', type: 'select', options: ['morning', 'afternoon', 'night'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'on_leave'] },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'hireDate', label: 'Hire Date', type: 'date' },
      { key: 'certifications', label: 'Certifications', type: 'textarea', fullWidth: true },
    ],
    defaultValues: { shift: 'morning', status: 'active' }
  },

  'ppe-detections': {
    title: 'PPE Detection Records',
    singular: 'PPE Detection',
    apiKey: 'ppeDetectionsAPI',
    hasAI: true,
    getItemTitle: (item) => `${item.employeeName} - ${item.zone}`,
    columns: [
      { key: 'employeeName', label: 'Employee' },
      { key: 'zone', label: 'Zone' },
      { key: 'complianceScore', label: 'Score', render: (v) => `${v}%` },
      { key: 'status', label: 'Status', badge: true },
      { key: 'helmet', label: 'Helmet', render: (v) => v ? 'Yes' : 'No' },
      { key: 'safetyVest', label: 'Vest', render: (v) => v ? 'Yes' : 'No' },
    ],
    fields: [
      { key: 'employeeName', label: 'Employee Name', type: 'text', required: true },
      { key: 'zone', label: 'Zone', type: 'text', required: true },
      { key: 'helmet', label: 'Helmet Detected', type: 'boolean' },
      { key: 'safetyVest', label: 'Safety Vest Detected', type: 'boolean' },
      { key: 'safetyGlasses', label: 'Safety Glasses Detected', type: 'boolean' },
      { key: 'gloves', label: 'Gloves Detected', type: 'boolean' },
      { key: 'safetyBoots', label: 'Safety Boots Detected', type: 'boolean' },
      { key: 'earProtection', label: 'Ear Protection Detected', type: 'boolean' },
      { key: 'complianceScore', label: 'Compliance Score (%)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['compliant', 'non_compliant', 'partial'] },
    ],
    defaultValues: { status: 'compliant', complianceScore: 0 }
  },

  'hazard-zones': {
    title: 'Hazard Zones',
    singular: 'Hazard Zone',
    apiKey: 'hazardZonesAPI',
    hasAI: true,
    getItemTitle: (item) => item.name,
    columns: [
      { key: 'name', label: 'Zone Name' },
      { key: 'type', label: 'Type', badge: true },
      { key: 'location', label: 'Location' },
      { key: 'riskLevel', label: 'Risk', badge: true },
      { key: 'currentOccupancy', label: 'Occupancy', render: (v, item) => `${v}/${item.maxOccupancy}` },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Zone Name', type: 'text', required: true },
      { key: 'type', label: 'Zone Type', type: 'select', options: ['restricted', 'caution', 'danger', 'safe'] },
      { key: 'location', label: 'Location', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'maxOccupancy', label: 'Max Occupancy', type: 'number' },
      { key: 'currentOccupancy', label: 'Current Occupancy', type: 'number' },
      { key: 'requiredPPE', label: 'Required PPE', type: 'textarea', fullWidth: true },
      { key: 'riskLevel', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'lockdown'] },
    ],
    defaultValues: { type: 'caution', riskLevel: 'medium', status: 'active', maxOccupancy: 10, currentOccupancy: 0 }
  },

  'incidents': {
    title: 'Incident Reports',
    singular: 'Incident',
    apiKey: 'incidentsAPI',
    hasAI: true,
    getItemTitle: (item) => `${item.incidentNumber} - ${item.title}`,
    columns: [
      { key: 'incidentNumber', label: 'Incident #' },
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type', badge: true },
      { key: 'severity', label: 'Severity', badge: true },
      { key: 'status', label: 'Status', badge: true },
      { key: 'date', label: 'Date', render: (v) => v ? new Date(v).toLocaleDateString() : '-' },
    ],
    fields: [
      { key: 'incidentNumber', label: 'Incident Number', type: 'text', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true, fullWidth: true },
      { key: 'type', label: 'Type', type: 'select', options: ['injury', 'near_miss', 'property_damage', 'environmental', 'fire', 'chemical_spill'], required: true },
      { key: 'severity', label: 'Severity', type: 'select', options: ['minor', 'moderate', 'major', 'critical'] },
      { key: 'location', label: 'Location', type: 'text', required: true },
      { key: 'reportedBy', label: 'Reported By', type: 'text', required: true },
      { key: 'assignedTo', label: 'Assigned To', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'investigating', 'resolved', 'closed'] },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'rootCause', label: 'Root Cause', type: 'textarea', fullWidth: true },
      { key: 'correctiveAction', label: 'Corrective Action', type: 'textarea', fullWidth: true },
    ],
    defaultValues: { status: 'open', severity: 'minor', type: 'near_miss' }
  },

  'safety-trainings': {
    title: 'Safety Training Programs',
    singular: 'Training',
    apiKey: 'safetyTrainingsAPI',
    hasAI: false,
    getItemTitle: (item) => item.title,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type', badge: true },
      { key: 'instructor', label: 'Instructor' },
      { key: 'scheduledDate', label: 'Date' },
      { key: 'currentParticipants', label: 'Enrolled', render: (v, item) => `${v}/${item.maxParticipants}` },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'title', label: 'Training Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'type', label: 'Type', type: 'select', options: ['osha_required', 'equipment', 'emergency', 'hazmat', 'general', 'ppe'], required: true },
      { key: 'instructor', label: 'Instructor', type: 'text', required: true },
      { key: 'duration', label: 'Duration', type: 'text' },
      { key: 'maxParticipants', label: 'Max Participants', type: 'number' },
      { key: 'currentParticipants', label: 'Current Participants', type: 'number' },
      { key: 'scheduledDate', label: 'Scheduled Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['scheduled', 'in_progress', 'completed', 'cancelled'] },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'certificationValid', label: 'Certification Valid For', type: 'text' },
    ],
    defaultValues: { status: 'scheduled', maxParticipants: 30, currentParticipants: 0 }
  },

  'equipment-inspections': {
    title: 'Equipment Inspections',
    singular: 'Inspection',
    apiKey: 'equipmentInspectionsAPI',
    hasAI: false,
    getItemTitle: (item) => `${item.equipmentName} (${item.equipmentId})`,
    columns: [
      { key: 'equipmentName', label: 'Equipment' },
      { key: 'equipmentId', label: 'ID' },
      { key: 'type', label: 'Type', badge: true },
      { key: 'inspector', label: 'Inspector' },
      { key: 'inspectionDate', label: 'Date' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'condition', label: 'Condition', badge: true },
    ],
    fields: [
      { key: 'equipmentName', label: 'Equipment Name', type: 'text', required: true },
      { key: 'equipmentId', label: 'Equipment ID', type: 'text', required: true },
      { key: 'type', label: 'Inspection Type', type: 'select', options: ['daily', 'weekly', 'monthly', 'annual'] },
      { key: 'inspector', label: 'Inspector', type: 'text', required: true },
      { key: 'inspectionDate', label: 'Inspection Date', type: 'date', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['passed', 'failed', 'needs_repair', 'out_of_service'] },
      { key: 'condition', label: 'Condition', type: 'select', options: ['excellent', 'good', 'fair', 'poor'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
      { key: 'nextInspectionDate', label: 'Next Inspection Date', type: 'date' },
    ],
    defaultValues: { type: 'daily', status: 'passed', condition: 'good' }
  },

  'safety-audits': {
    title: 'Safety Audits',
    singular: 'Audit',
    apiKey: 'safetyAuditsAPI',
    hasAI: true,
    getItemTitle: (item) => `${item.auditNumber} - ${item.title}`,
    columns: [
      { key: 'auditNumber', label: 'Audit #' },
      { key: 'title', label: 'Title' },
      { key: 'department', label: 'Department' },
      { key: 'score', label: 'Score', render: (v, item) => item.maxScore ? `${v}/${item.maxScore}` : v },
      { key: 'auditDate', label: 'Date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'auditNumber', label: 'Audit Number', type: 'text', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'auditor', label: 'Auditor', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'text', required: true },
      { key: 'auditDate', label: 'Audit Date', type: 'date', required: true },
      { key: 'score', label: 'Score', type: 'number' },
      { key: 'maxScore', label: 'Max Score', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['scheduled', 'in_progress', 'completed', 'follow_up'] },
      { key: 'findings', label: 'Findings', type: 'textarea', fullWidth: true },
      { key: 'recommendations', label: 'Recommendations', type: 'textarea', fullWidth: true },
    ],
    defaultValues: { status: 'scheduled', score: 0, maxScore: 100 }
  },

  'emergency-contacts': {
    title: 'Emergency Contacts',
    singular: 'Contact',
    apiKey: 'emergencyContactsAPI',
    hasAI: false,
    getItemTitle: (item) => `${item.name} - ${item.role}`,
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'role', label: 'Role' },
      { key: 'department', label: 'Department' },
      { key: 'phone', label: 'Phone' },
      { key: 'type', label: 'Type', badge: true },
      { key: 'available24x7', label: '24/7', render: (v) => v ? 'Yes' : 'No' },
    ],
    fields: [
      { key: 'name', label: 'Contact Name', type: 'text', required: true },
      { key: 'role', label: 'Role/Title', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'text', required: true },
      { key: 'phone', label: 'Phone', type: 'text', required: true },
      { key: 'alternatePhone', label: 'Alternate Phone', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['internal', 'external', 'medical', 'fire', 'hazmat'] },
      { key: 'available24x7', label: 'Available 24/7', type: 'boolean' },
      { key: 'priority', label: 'Priority (1=highest)', type: 'number' },
    ],
    defaultValues: { type: 'internal', available24x7: false, priority: 1 }
  },

  'ppe-inventory': {
    title: 'PPE Inventory',
    singular: 'PPE Item',
    apiKey: 'ppeInventoryAPI',
    hasAI: false,
    getItemTitle: (item) => item.itemName,
    columns: [
      { key: 'itemName', label: 'Item' },
      { key: 'category', label: 'Category', badge: true },
      { key: 'quantity', label: 'Qty', render: (v, item) => `${v} (min: ${item.minQuantity})` },
      { key: 'unitCost', label: 'Unit Cost', render: (v) => `$${Number(v).toFixed(2)}` },
      { key: 'location', label: 'Location' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'itemName', label: 'Item Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['head', 'eye', 'ear', 'hand', 'foot', 'body', 'respiratory'], required: true },
      { key: 'brand', label: 'Brand', type: 'text' },
      { key: 'quantity', label: 'Quantity', type: 'number' },
      { key: 'minQuantity', label: 'Min Quantity', type: 'number' },
      { key: 'unitCost', label: 'Unit Cost ($)', type: 'number' },
      { key: 'location', label: 'Storage Location', type: 'text' },
      { key: 'expirationDate', label: 'Expiration Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['in_stock', 'low_stock', 'out_of_stock', 'expired'] },
      { key: 'lastRestocked', label: 'Last Restocked', type: 'date' },
      { key: 'supplier', label: 'Supplier', type: 'text' },
    ],
    defaultValues: { status: 'in_stock', quantity: 0, minQuantity: 10, unitCost: 0, category: 'head' }
  },

  'compliance-reports': {
    title: 'Compliance Reports',
    singular: 'Report',
    apiKey: 'complianceReportsAPI',
    hasAI: true,
    getItemTitle: (item) => `${item.reportNumber} - ${item.title}`,
    columns: [
      { key: 'reportNumber', label: 'Report #' },
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type', badge: true },
      { key: 'period', label: 'Period' },
      { key: 'complianceRate', label: 'Rate', render: (v) => `${v}%` },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'reportNumber', label: 'Report Number', type: 'text', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'type', label: 'Report Type', type: 'select', options: ['osha_300', 'osha_301', 'osha_300a', 'monthly', 'quarterly', 'annual'], required: true },
      { key: 'period', label: 'Period', type: 'text', required: true },
      { key: 'preparedBy', label: 'Prepared By', type: 'text', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'review', 'submitted', 'approved'] },
      { key: 'totalIncidents', label: 'Total Incidents', type: 'number' },
      { key: 'totalTrainings', label: 'Total Trainings', type: 'number' },
      { key: 'complianceRate', label: 'Compliance Rate (%)', type: 'number' },
      { key: 'summary', label: 'Summary', type: 'textarea', fullWidth: true },
      { key: 'submissionDate', label: 'Submission Date', type: 'date' },
    ],
    defaultValues: { status: 'draft', totalIncidents: 0, totalTrainings: 0, complianceRate: 0 }
  },

  'shift-schedules': {
    title: 'Shift Schedules',
    singular: 'Schedule',
    apiKey: 'shiftSchedulesAPI',
    hasAI: false,
    getItemTitle: (item) => `${item.employeeName} - ${item.date}`,
    columns: [
      { key: 'employeeName', label: 'Employee' },
      { key: 'department', label: 'Department' },
      { key: 'shift', label: 'Shift', badge: true },
      { key: 'date', label: 'Date' },
      { key: 'startTime', label: 'Start' },
      { key: 'endTime', label: 'End' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'employeeName', label: 'Employee Name', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'text', required: true },
      { key: 'shift', label: 'Shift', type: 'select', options: ['morning', 'afternoon', 'night'], required: true },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'startTime', label: 'Start Time', type: 'text', required: true },
      { key: 'endTime', label: 'End Time', type: 'text', required: true },
      { key: 'zone', label: 'Assigned Zone', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['scheduled', 'active', 'completed', 'absent', 'swapped'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true },
    ],
    defaultValues: { shift: 'morning', status: 'scheduled', startTime: '06:00', endTime: '14:00' }
  },

  'risk-assessments': {
    title: 'Risk Assessments',
    singular: 'Risk Assessment',
    apiKey: 'riskAssessmentsAPI',
    hasAI: true,
    getItemTitle: (item) => item.title,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'area', label: 'Area' },
      { key: 'likelihood', label: 'Likelihood', badge: true },
      { key: 'consequence', label: 'Consequence', badge: true },
      { key: 'riskLevel', label: 'Risk Level', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'title', label: 'Assessment Title', type: 'text', required: true },
      { key: 'area', label: 'Area/Location', type: 'text', required: true },
      { key: 'assessor', label: 'Assessor', type: 'text', required: true },
      { key: 'assessmentDate', label: 'Assessment Date', type: 'date', required: true },
      { key: 'hazardDescription', label: 'Hazard Description', type: 'textarea', required: true, fullWidth: true },
      { key: 'likelihood', label: 'Likelihood', type: 'select', options: ['rare', 'unlikely', 'possible', 'likely', 'certain'] },
      { key: 'consequence', label: 'Consequence', type: 'select', options: ['negligible', 'minor', 'moderate', 'major', 'catastrophic'] },
      { key: 'riskLevel', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'extreme'] },
      { key: 'controls', label: 'Control Measures', type: 'textarea', fullWidth: true },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'mitigated', 'accepted', 'closed'] },
    ],
    defaultValues: { status: 'open', likelihood: 'possible', consequence: 'moderate', riskLevel: 'medium' }
  },

  'safety-alerts': {
    title: 'Safety Alerts',
    singular: 'Alert',
    apiKey: 'safetyAlertsAPI',
    hasAI: false,
    getItemTitle: (item) => item.title,
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type', badge: true },
      { key: 'zone', label: 'Zone' },
      { key: 'priority', label: 'Priority', badge: true },
      { key: 'issuedBy', label: 'Issued By' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'title', label: 'Alert Title', type: 'text', required: true },
      { key: 'message', label: 'Alert Message', type: 'textarea', required: true, fullWidth: true },
      { key: 'type', label: 'Alert Type', type: 'select', options: ['warning', 'danger', 'info', 'critical'] },
      { key: 'zone', label: 'Affected Zone', type: 'text' },
      { key: 'issuedBy', label: 'Issued By', type: 'text', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'acknowledged', 'resolved', 'expired'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'urgent'] },
    ],
    defaultValues: { type: 'warning', status: 'active', priority: 'medium' }
  }
};
